name: Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: デプロイ先の環境
        required: true
        type: environment
        default: development

jobs:
  print:
    runs-on: ubuntu-20.04

    steps:
      - name: print
        run: echo "GitHub Actions Implementation Test"
